In [2]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv

In [4]:
df = pd.read_csv("diabetes.csv")

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [10]:
x = df.iloc[:,:-1]
y= df.iloc[:,-1]

In [11]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72.0,35,169.5,33.6,0.627,50
1,1,85,66.0,29,102.5,26.6,0.351,31
2,8,183,64.0,32,169.5,23.3,0.672,32
3,1,89,66.0,23,94.0,28.1,0.167,21
4,0,137,40.0,35,168.0,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76.0,48,180.0,32.9,0.171,63
764,2,122,70.0,27,102.5,36.8,0.340,27
765,5,121,72.0,23,112.0,26.2,0.245,30
766,1,126,60.0,32,169.5,30.1,0.349,47
767,1,93,70.0,31,102.5,30.4,0.315,23

In [12]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
scaler.fit_transform(x)

array([[ 0.63994726,  0.86462486, -0.03218035, ...,  0.16948251,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.20472661, -0.52812374, ..., -0.84854874,
        -0.36506078, -0.19067191],
       [ 1.23388019,  2.01426457, -0.69343821, ..., -1.32847775,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 , -0.02224005, -0.03218035, ..., -0.90672195,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.14199419, -1.02406713, ..., -0.33953311,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.94195182, -0.19749482, ..., -0.2959032 ,
        -0.47378505, -0.87137393]])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=2,test_size=0.2)

In [16]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Input

In [17]:
model = Sequential()
model.add(Input(shape=(8,)))
model.add(Dense(32,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [56]:
model.compile(optimizer="RMSprop",loss="binary_crossentropy",metrics=["accuracy"])

In [57]:
model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7997 - loss: 0.5664 - val_accuracy: 0.5065 - val_loss: 1.1974
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4758 - val_accuracy: 0.6104 - val_loss: 0.9166
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4964 - val_accuracy: 0.7727 - val_loss: 0.5610
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4658 - val_accuracy: 0.7143 - val_loss: 0.8255
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4852 - val_accuracy: 0.7143 - val_loss: 1.2409
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8062 - loss: 0.5137 - val_accuracy: 0.7403 - val_loss: 0.6078
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7948 - loss: 0.4920 - val_accuracy: 0.7597 - val_loss: 0.5167
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.8078 - loss: 0.4660 - val_accuracy: 0.6234 - val_loss: 1.0137
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4927 - val_accuracy: 0.7208 - val_loss: 1.0026
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4572 - val_accuracy: 0.7597 - val_loss: 0.5221
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4944 - val_accuracy: 0.7273 - val_loss: 0.6061
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.5158 - val_accuracy: 0.5519 - val_loss: 1.0115
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4857 - val_accuracy: 0.7727 - val_loss: 0.4972
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4906 - val_accuracy: 0.7468 - val_loss: 0.6437
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4724 - val_accuracy: 0.7532 - val_loss: 0.5145
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4516 - val_accuracy: 0.7532 - val_loss: 0.6085
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.5039 - val_accuracy: 0.7078 - val_loss: 0.6490
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4318 - val_accuracy: 0.7338 - val_loss: 0.5693
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.5003 - val_accuracy: 0.7532 - val_loss: 0.5298
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.5122 - val_accuracy: 0.7208 - val_loss: 0.9555
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4578 - val_accuracy: 0.7468 - val_loss: 0.6206
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4568 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.5036 - val_accuracy: 0.7078 - val_loss: 0.7954
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4862 - val_accuracy: 0.6558 - val_loss: 0.8926
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4689 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4827 - val_accuracy: 0.7727 - val_loss: 0.5476
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4760 - val_accuracy: 0.7792 - val_loss: 0.4584
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4377 - val_accuracy: 0.7208 - val_loss: 0.6002
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.5100 - val_accuracy: 0.7273 - val_loss: 0.5619
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4640 - val_accuracy: 0.7597 - val_loss: 0.5042
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4525 - val_accuracy: 0.7792 - val_loss: 0.5815
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.4574 - val_accuracy: 0.7338 - val_loss: 0.5630
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4749 - val_accuracy: 0.7208 - val_loss: 0.5825
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4528 - val_accuracy: 0.7922 - val_loss: 0.4838
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4339 - val_accuracy: 0.7857 - val_loss: 0.4612
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4933 - val_accuracy: 0.7662 - val_loss: 0.4925
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4595 - val_accuracy: 0.7013 - val_loss: 0.6962
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4618 - val_accuracy: 0.7597 - val_loss: 0.5086
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.4243 - val_accuracy: 0.6818 - val_loss: 0.8325
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4956 - val_accuracy: 0.6818 - val_loss: 0.7655
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4578 - val_accuracy: 0.7143 - val_loss: 0.6339
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4569 - val_accuracy: 0.7792 - val_loss: 0.5590
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4833 - val_accuracy: 0.7338 - val_loss: 0.5809
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4538 - val_accuracy: 0.4286 - val_loss: 1.5697
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.5180 - val_accuracy: 0.7208 - val_loss: 0.6167
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4880 - val_accuracy: 0.7857 - val_loss: 0.4527
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4514 - val_accuracy: 0.7143 - val_loss: 0.7735
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.4593 - val_accuracy: 0.7727 - val_loss: 0.4657
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4500 - val_accuracy: 0.7078 - val_loss: 0.6648
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4835 - val_accuracy: 0.7922 - val_loss: 0.4611
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4524 - val_accuracy: 0.6364 - val_loss: 1.0206
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.5300 - val_accuracy: 0.7468 - val_loss: 0.5601
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.4469 - val_accuracy: 0.7662 - val_loss: 0.4940
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4637 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4491 - val_accuracy: 0.6948 - val_loss: 0.6844
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8046 - loss: 0.4455 - val_accuracy: 0.7013 - val_loss: 0.6868
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4705 - val_accuracy: 0.7727 - val_loss: 0.4866
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4465 - val_accuracy: 0.6818 - val_loss: 0.7440
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4793 - val_accuracy: 0.5000 - val_loss: 1.3233
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4674 - val_accuracy: 0.7078 - val_loss: 0.6896
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4850 - val_accuracy: 0.7403 - val_loss: 0.5675
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4537 - val_accuracy: 0.7662 - val_loss: 0.5753
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4781 - val_accuracy: 0.7857 - val_loss: 0.4775
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4576 - val_accuracy: 0.7468 - val_loss: 0.5759
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4507 - val_accuracy: 0.7468 - val_loss: 0.6667
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4612 - val_accuracy: 0.7532 - val_loss: 0.6291
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4399 - val_accuracy: 0.7922 - val_loss: 0.4533
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4791 - val_accuracy: 0.7857 - val_loss: 0.4562
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4622 - val_accuracy: 0.7727 - val_loss: 0.5368
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4574 - val_accuracy: 0.5974 - val_loss: 0.9657
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4187 - val_accuracy: 0.7208 - val_loss: 0.7394
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4829 - val_accuracy: 0.7403 - val_loss: 0.5275
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4479 - val_accuracy: 0.7662 - val_loss: 0.5425
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4778 - val_accuracy: 0.7922 - val_loss: 0.4686
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4526 - val_accuracy: 0.7597 - val_loss: 0.5501
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3987 - val_accuracy: 0.7792 - val_loss: 0.4837
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4878 - val_accuracy: 0.7597 - val_loss: 0.4799
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4213 - val_accuracy: 0.7662 - val_loss: 0.4743
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.5017 - val_accuracy: 0.7727 - val_loss: 0.4796
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.4229 - val_accuracy: 0.7597 - val_loss: 0.5938
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4353 - val_accuracy: 0.8052 - val_loss: 0.4537
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4411 - val_accuracy: 0.7792 - val_loss: 0.4600
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.4338 - val_accuracy: 0.7857 - val_loss: 0.4759
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4749 - val_accuracy: 0.7987 - val_loss: 0.4616
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4632 - val_accuracy: 0.7922 - val_loss: 0.4503
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4708 - val_accuracy: 0.7987 - val_loss: 0.4496
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4376 - val_accuracy: 0.7338 - val_loss: 0.6950
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4891 - val_accuracy: 0.7143 - val_loss: 0.7609
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4643 - val_accuracy: 0.7792 - val_loss: 0.4984
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.4218 - val_accuracy: 0.7987 - val_loss: 0.4506
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4249 - val_accuracy: 0.5130 - val_loss: 1.2217
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.5084 - val_accuracy: 0.7662 - val_loss: 0.4919
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3866 - val_accuracy: 0.8182 - val_loss: 0.4535
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4782 - val_accuracy: 0.7468 - val_loss: 0.6534
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4288 - val_accuracy: 0.8052 - val_loss: 0.4474
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4384 - val_accuracy: 0.7857 - val_loss: 0.4655
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4615 - val_accuracy: 0.7338 - val_loss: 0.5973
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4408 - val_accuracy: 0.7468 - val_loss: 0.5614
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4409 - val_accuracy: 0.7143 - val_loss: 0.7400
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4466 - val_accuracy: 0.7662 - val_loss: 0.5593

Here we have generated a model but still we have confusion about whether our optimizer is good enough. Should I change it to another and try again and again? Are the number of my hidden layers enough, are the number of my neurons enough, and are many other parameters enough to overcome this problem? To overcome this problem we have Keras Tuner, which tunes the hyperparameters and tells us which parameter will fit much better (such as the number of neurons, the number of hidden layers, the optimizer, etc.).

Here we are going to do it in different orders:
1. How to select the output up to `max`
2. Number of nodes in a layer
3. How to select the number of layers
4. All in one model

In [21]:
!pip install keras-tuner -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 8.6 MB/s eta 0:00:00

1]Hyper-tuning optimizers only for now.

In [22]:
import keras_tuner as kt

In [65]:
def build_model(hp):
  model=Sequential()
  model.add(Input(shape=(8,)))
  model.add(Dense(32,activation="relu"))
  model.add(Dense(1,activation="sigmoid"))
  optimizer = hp.Choice("optimizer",values=["adam","sgd","rsmprop","adadelta"])
  model.compile(optimizer=optimizer,loss="binary_crossentropy",metrics=["accuracy"])
  return model

In [66]:
tuner=kt.RandomSearch(build_model,max_trials=5,objective="val_accuracy")

Reloading Tuner from ./untitled_project/tuner0.json

In [67]:
tuner.search(x_train,y_train,epochs=7,validation_data=(x_test,y_test))

In [68]:
tuner.get_best_hyperparameters(num_trials=1)[0].values

{'optimizer': 'Adam'}

In [69]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [70]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [71]:
model.fit(x_train,y_train,epochs=100,initial_epoch=8,validation_data=(x_test,y_test))

Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7296 - loss: 0.9052 - val_accuracy: 0.7403 - val_loss: 0.6563
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.6986 - val_accuracy: 0.6818 - val_loss: 0.7479
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.6377 - val_accuracy: 0.7338 - val_loss: 0.5874
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.5466 - val_accuracy: 0.7727 - val_loss: 0.5575
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.5495 - val_accuracy: 0.7208 - val_loss: 0.6020
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.5292 - val_accuracy: 0.7792 - val_loss: 0.5586
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.5487 - val_accuracy: 0.7532 - val_loss: 0.5731
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.5305 - val_accuracy: 0.7338 - val_loss: 0.5782
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.5421 - val_accuracy: 0.7792 - val_loss: 0.5434
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.5313 - val_accuracy: 0.7338 - val_loss: 0.5764
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.5372 - val_accuracy: 0.7338 - val_loss: 0.7149
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7329 - loss: 0.5981 - val_accuracy: 0.7727 - val_loss: 0.5280
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4988 - val_accuracy: 0.7727 - val_loss: 0.5313
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4918 - val_accuracy: 0.7468 - val_loss: 0.5616
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.5015 - val_accuracy: 0.7597 - val_loss: 0.5271
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4860 - val_accuracy: 0.7727 - val_loss: 0.5466
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4930 - val_accuracy: 0.7922 - val_loss: 0.5453
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4887 - val_accuracy: 0.7338 - val_loss: 0.5644
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4905 - val_accuracy: 0.7662 - val_loss: 0.5133
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4713 - val_accuracy: 0.7662 - val_loss: 0.5158
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4870 - val_accuracy: 0.7727 - val_loss: 0.5161
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4782 - val_accuracy: 0.7338 - val_loss: 0.5302
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4755 - val_accuracy: 0.7792 - val_loss: 0.5173
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4798 - val_accuracy: 0.7338 - val_loss: 0.5776
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.5040 - val_accuracy: 0.7857 - val_loss: 0.5276
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4982 - val_accuracy: 0.7792 - val_loss: 0.5075
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4991 - val_accuracy: 0.7857 - val_loss: 0.5135
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4864 - val_accuracy: 0.6883 - val_loss: 0.7388
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5716 - val_accuracy: 0.7857 - val_loss: 0.5576
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.5232 - val_accuracy: 0.7662 - val_loss: 0.5070
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4728 - val_accuracy: 0.7532 - val_loss: 0.5144
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4651 - val_accuracy: 0.7403 - val_loss: 0.5281
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4833 - val_accuracy: 0.7662 - val_loss: 0.5034
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4523 - val_accuracy: 0.7468 - val_loss: 0.5447
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4630 - val_accuracy: 0.7597 - val_loss: 0.5122
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4811 - val_accuracy: 0.7727 - val_loss: 0.4926
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4507 - val_accuracy: 0.7792 - val_loss: 0.4952
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4782 - val_accuracy: 0.7727 - val_loss: 0.5082
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4710 - val_accuracy: 0.7727 - val_loss: 0.5059
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4698 - val_accuracy: 0.6753 - val_loss: 0.7864
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.5298 - val_accuracy: 0.7403 - val_loss: 0.5099
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4865 - val_accuracy: 0.7792 - val_loss: 0.4857
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4966 - val_accuracy: 0.7403 - val_loss: 0.5337
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4461 - val_accuracy: 0.7403 - val_loss: 0.5266
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4366 - val_accuracy: 0.7662 - val_loss: 0.4938
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4543 - val_accuracy: 0.7468 - val_loss: 0.4974
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4382 - val_accuracy: 0.7727 - val_loss: 0.4847
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4497 - val_accuracy: 0.7662 - val_loss: 0.4811
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4508 - val_accuracy: 0.7792 - val_loss: 0.4949
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4395 - val_accuracy: 0.7597 - val_loss: 0.4911
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4362 - val_accuracy: 0.7597 - val_loss: 0.4883
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4367 - val_accuracy: 0.7792 - val_loss: 0.4844
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4374 - val_accuracy: 0.7532 - val_loss: 0.4997
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4697 - val_accuracy: 0.7792 - val_loss: 0.4915
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.4470 - val_accuracy: 0.7468 - val_loss: 0.5446
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4580 - val_accuracy: 0.7532 - val_loss: 0.4959
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4403 - val_accuracy: 0.7922 - val_loss: 0.4849
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4899 - val_accuracy: 0.7662 - val_loss: 0.4969
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4496 - val_accuracy: 0.7792 - val_loss: 0.4809
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4603 - val_accuracy: 0.7597 - val_loss: 0.4970
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4532 - val_accuracy: 0.7662 - val_loss: 0.4866
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4399 - val_accuracy: 0.7857 - val_loss: 0.4900
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4355 - val_accuracy: 0.7922 - val_loss: 0.4782
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4306 - val_accuracy: 0.7468 - val_loss: 0.5153
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4281 - val_accuracy: 0.7792 - val_loss: 0.4744
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.4449 - val_accuracy: 0.7857 - val_loss: 0.4782
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4273 - val_accuracy: 0.7662 - val_loss: 0.4883
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4434 - val_accuracy: 0.7532 - val_loss: 0.4868
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4717 - val_accuracy: 0.7273 - val_loss: 0.5440
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4950 - val_accuracy: 0.7662 - val_loss: 0.4713
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8176 - loss: 0.4344 - val_accuracy: 0.7662 - val_loss: 0.4858
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8062 - loss: 0.4458 - val_accuracy: 0.7857 - val_loss: 0.4816
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.4293 - val_accuracy: 0.7792 - val_loss: 0.4780
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4705 - val_accuracy: 0.7792 - val_loss: 0.4756
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7622 - loss: 0.5396 - val_accuracy: 0.7857 - val_loss: 0.4698
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8192 - loss: 0.4285 - val_accuracy: 0.7857 - val_loss: 0.4796
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4486 - val_accuracy: 0.7792 - val_loss: 0.4919
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8127 - loss: 0.4271 - val_accuracy: 0.7857 - val_loss: 0.4677
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8388 - loss: 0.4115 - val_accuracy: 0.7662 - val_loss: 0.4983
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8208 - loss: 0.4219 - val_accuracy: 0.7662 - val_loss: 0.4828
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4203 - val_accuracy: 0.7857 - val_loss: 0.4715
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.4151 - val_accuracy: 0.7792 - val_loss: 0.4703
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4511 - val_accuracy: 0.7403 - val_loss: 0.5615
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4280 - val_accuracy: 0.7468 - val_loss: 0.5081
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4340 - val_accuracy: 0.7727 - val_loss: 0.4824
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.4341 - val_accuracy: 0.7857 - val_loss: 0.4654
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4684
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4389 - val_accuracy: 0.7662 - val_loss: 0.4888
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4523 - val_accuracy: 0.7727 - val_loss: 0.4918
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.4197 - val_accuracy: 0.7727 - val_loss: 0.4854
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4299 - val_accuracy: 0.7792 - val_loss: 0.4661
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.4102 - val_accuracy: 0.7727 - val_loss: 0.4837

See getting a much better result after hyperparameter tuning.

2] we are doing it for the number of nodes my hidden layer should have.

In [114]:
def build_models(hp):
  model=Sequential()
  units=hp.Int("units",min_value=8,max_value=128,step=8)
  model.add(Input(shape=(8,)))
  model.add(Dense(units=units,activation="relu"))
  model.add(Dense(1,activation="sigmoid"))
  model.compile(optimizer="Adam",loss="binary_crossentropy",metrics=["accuracy"])
  return model

In [115]:
tuner = kt.RandomSearch(build_models,max_trials=5,objective="val_accuracy",directory="mydir")

Reloading Tuner from mydir/untitled_project/tuner0.json

In [116]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [117]:
tuner.get_best_hyperparameters()[0].values

{'units': 72}

In [118]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [119]:
model.fit(x_train,y_train,epochs=100,initial_epoch=6,batch_size=32,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7182 - loss: 0.6253 - val_accuracy: 0.7273 - val_loss: 0.6414
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.5213 - val_accuracy: 0.7468 - val_loss: 0.5997
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7492 - loss: 0.5379 - val_accuracy: 0.6494 - val_loss: 0.6534
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7459 - loss: 0.5757 - val_accuracy: 0.7143 - val_loss: 0.6770
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.5414 - val_accuracy: 0.8117 - val_loss: 0.5139
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.5007 - val_accuracy: 0.7662 - val_loss: 0.5368
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.5627 - val_accuracy: 0.7987 - val_loss: 0.5056
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4991 - val_accuracy: 0.7857 - val_loss: 0.5230
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5299 - val_accuracy: 0.7403 - val_loss: 0.5713
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5505 - val_accuracy: 0.7922 - val_loss: 0.5007
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4742 - val_accuracy: 0.7792 - val_loss: 0.5009
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4756 - val_accuracy: 0.7727 - val_loss: 0.5220
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4688 - val_accuracy: 0.7597 - val_loss: 0.5250
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4733 - val_accuracy: 0.7792 - val_loss: 0.4973
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4624 - val_accuracy: 0.7662 - val_loss: 0.5920
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4841 - val_accuracy: 0.7143 - val_loss: 0.6176
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4708 - val_accuracy: 0.7532 - val_loss: 0.5819
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.5382 - val_accuracy: 0.7468 - val_loss: 0.6017
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.5225 - val_accuracy: 0.7922 - val_loss: 0.5063
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.5238 - val_accuracy: 0.7468 - val_loss: 0.5621
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4562 - val_accuracy: 0.7468 - val_loss: 0.5255
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4824 - val_accuracy: 0.7987 - val_loss: 0.4842
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4402 - val_accuracy: 0.8052 - val_loss: 0.4779
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4603 - val_accuracy: 0.7597 - val_loss: 0.5213
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4349 - val_accuracy: 0.7338 - val_loss: 0.5856
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4637 - val_accuracy: 0.7987 - val_loss: 0.4817
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4483 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4186 - val_accuracy: 0.7987 - val_loss: 0.4842
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4341 - val_accuracy: 0.7922 - val_loss: 0.4992
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4309 - val_accuracy: 0.8052 - val_loss: 0.4922
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4308 - val_accuracy: 0.7857 - val_loss: 0.4710
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5079 - val_accuracy: 0.8052 - val_loss: 0.4972
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4792 - val_accuracy: 0.8052 - val_loss: 0.4672
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4272 - val_accuracy: 0.7338 - val_loss: 0.5521
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4638 - val_accuracy: 0.7597 - val_loss: 0.4905
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4341 - val_accuracy: 0.7922 - val_loss: 0.4622
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4030 - val_accuracy: 0.7727 - val_loss: 0.4927
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.4046 - val_accuracy: 0.8052 - val_loss: 0.4990
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4211 - val_accuracy: 0.7078 - val_loss: 0.5730
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4850 - val_accuracy: 0.7273 - val_loss: 0.6212
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.5261 - val_accuracy: 0.8117 - val_loss: 0.4533
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4426 - val_accuracy: 0.7013 - val_loss: 0.6581
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4265 - val_accuracy: 0.8052 - val_loss: 0.4494
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4447 - val_accuracy: 0.7078 - val_loss: 0.7275
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.5799 - val_accuracy: 0.7208 - val_loss: 0.7103
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.5071 - val_accuracy: 0.8312 - val_loss: 0.4410
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.4149 - val_accuracy: 0.8052 - val_loss: 0.4727
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4616 - val_accuracy: 0.7338 - val_loss: 0.5064
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4421 - val_accuracy: 0.8247 - val_loss: 0.4398
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3964 - val_accuracy: 0.8182 - val_loss: 0.4370
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3937 - val_accuracy: 0.7208 - val_loss: 0.5775
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.4330 - val_accuracy: 0.8312 - val_loss: 0.4604
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4293 - val_accuracy: 0.8052 - val_loss: 0.4986
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4862 - val_accuracy: 0.7273 - val_loss: 0.5386
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4354 - val_accuracy: 0.7078 - val_loss: 0.6323
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4327 - val_accuracy: 0.8052 - val_loss: 0.4558
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.4029 - val_accuracy: 0.7987 - val_loss: 0.5230
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4667 - val_accuracy: 0.8052 - val_loss: 0.4405
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3961 - val_accuracy: 0.7338 - val_loss: 0.5895
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4167 - val_accuracy: 0.7922 - val_loss: 0.4649
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3853 - val_accuracy: 0.8247 - val_loss: 0.4305
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.4213 - val_accuracy: 0.7662 - val_loss: 0.5299
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.4072 - val_accuracy: 0.7403 - val_loss: 0.5073
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3891 - val_accuracy: 0.7727 - val_loss: 0.5071
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3836 - val_accuracy: 0.7922 - val_loss: 0.4495
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.4024 - val_accuracy: 0.7857 - val_loss: 0.4794
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4398 - val_accuracy: 0.7143 - val_loss: 0.6175
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4587 - val_accuracy: 0.7857 - val_loss: 0.4704
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.5042 - val_accuracy: 0.8182 - val_loss: 0.5026
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.4130 - val_accuracy: 0.7078 - val_loss: 0.6169
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4297 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4288 - val_accuracy: 0.7792 - val_loss: 0.4627
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3721 - val_accuracy: 0.7922 - val_loss: 0.4507
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4135 - val_accuracy: 0.8182 - val_loss: 0.4498
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3810 - val_accuracy: 0.8442 - val_loss: 0.4294
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8485 - loss: 0.3729 - val_accuracy: 0.8117 - val_loss: 0.4321
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3980 - val_accuracy: 0.8117 - val_loss: 0.4381
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8502 - loss: 0.3830 - val_accuracy: 0.8052 - val_loss: 0.4323
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.4152 - val_accuracy: 0.8442 - val_loss: 0.4340
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8306 - loss: 0.3791 - val_accuracy: 0.7727 - val_loss: 0.4496
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8485 - loss: 0.3655 - val_accuracy: 0.8117 - val_loss: 0.4886
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.4237 - val_accuracy: 0.7922 - val_loss: 0.4746
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3752 - val_accuracy: 0.7208 - val_loss: 0.5610
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8469 - loss: 0.3750 - val_accuracy: 0.8182 - val_loss: 0.4284
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8453 - loss: 0.3591 - val_accuracy: 0.7857 - val_loss: 0.4466
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8290 - loss: 0.3873 - val_accuracy: 0.6364 - val_loss: 0.8481
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4374 - val_accuracy: 0.8182 - val_loss: 0.4682
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8355 - loss: 0.3810 - val_accuracy: 0.8052 - val_loss: 0.4375
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8485 - loss: 0.3653 - val_accuracy: 0.8312 - val_loss: 0.4200
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8599 - loss: 0.3566 - val_accuracy: 0.8377 - val_loss: 0.4302
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8502 - loss: 0.3727 - val_accuracy: 0.8312 - val_loss: 0.4191
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3561 - val_accuracy: 0.8117 - val_loss: 0.4702
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3849 - val_accuracy: 0.8117 - val_loss: 0.4662
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4251 - val_accuracy: 0.8182 - val_loss: 0.4298

3], how to select the number of layers?

In [128]:
def build_model(hp):
  model=Sequential()
  model.add(Input(shape=(8,)))
  num_layers = hp.Int(
    "num_layers",
    min_value=1,
    max_value=10
)
  for i in range(num_layers):
    model.add(Dense(72,activation="relu"))
  model.add(Dense(1,activation="sigmoid"))
  model.compile(loss="binary_crossentropy",optimizer="Adam",metrics=["accuracy"])
  return model

In [129]:
tuner = kt.RandomSearch(build_model,objective="val_accuracy",max_trials=5, directory="mydir",
    project_name="num_layers_new",
    overwrite=True)

In [130]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7467532753944397

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 18s

In [140]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 6}

In [141]:
model = tuner.get_best_models(num_models=1)[0]

In [146]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,initial_epoch=6)

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9967 - loss: 0.0150 - val_accuracy: 0.8247 - val_loss: 1.3451
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0129 - val_accuracy: 0.8377 - val_loss: 1.3043
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0127 - val_accuracy: 0.8182 - val_loss: 1.3962
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0115 - val_accuracy: 0.8182 - val_loss: 1.3675
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0479 - val_accuracy: 0.8052 - val_loss: 1.2956
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.2874 - val_accuracy: 0.8117 - val_loss: 1.0338
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.1875 - val_accuracy: 0.7987 - val_loss: 0.7919
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1619 - val_accuracy: 0.7987 - val_loss: 0.9092
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9609 - loss: 0.1048 - val_accuracy: 0.7922 - val_loss: 0.8726
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0703 - val_accuracy: 0.7987 - val_loss: 1.0042
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9756 - loss: 0.0839 - val_accuracy: 0.7922 - val_loss: 1.1263
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9267 - loss: 0.2332 - val_accuracy: 0.7468 - val_loss: 0.8279
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8795 - loss: 0.2926 - val_accuracy: 0.7987 - val_loss: 0.8956
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9218 - loss: 0.1809 - val_accuracy: 0.7857 - val_loss: 0.8777
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9430 - loss: 0.1266 - val_accuracy: 0.8506 - val_loss: 0.6130
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9723 - loss: 0.0773 - val_accuracy: 0.7857 - val_loss: 0.8941
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9821 - loss: 0.0550 - val_accuracy: 0.7987 - val_loss: 1.0380
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9772 - loss: 0.0783 - val_accuracy: 0.7922 - val_loss: 0.8689
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9756 - loss: 0.0612 - val_accuracy: 0.8052 - val_loss: 0.8290
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0424 - val_accuracy: 0.7922 - val_loss: 0.9184
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9919 - loss: 0.0305 - val_accuracy: 0.7857 - val_loss: 1.0289
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0270 - val_accuracy: 0.7792 - val_loss: 1.0555
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9902 - loss: 0.0254 - val_accuracy: 0.8117 - val_loss: 1.0513
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0206 - val_accuracy: 0.7857 - val_loss: 1.2169
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0266 - val_accuracy: 0.8182 - val_loss: 1.1329
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0283 - val_accuracy: 0.7662 - val_loss: 1.1940
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0180 - val_accuracy: 0.8182 - val_loss: 1.0806
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0202 - val_accuracy: 0.7857 - val_loss: 1.1725
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0160 - val_accuracy: 0.7987 - val_loss: 1.2106
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0143 - val_accuracy: 0.8052 - val_loss: 1.2092
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0114 - val_accuracy: 0.7922 - val_loss: 1.2516
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0093 - val_accuracy: 0.7987 - val_loss: 1.2416
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0092 - val_accuracy: 0.8117 - val_loss: 1.2526
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0083 - val_accuracy: 0.7857 - val_loss: 1.3060
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0102 - val_accuracy: 0.7987 - val_loss: 1.2788
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0484 - val_accuracy: 0.7987 - val_loss: 1.2031
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9756 - loss: 0.0597 - val_accuracy: 0.7857 - val_loss: 1.2276
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0507 - val_accuracy: 0.7792 - val_loss: 1.2706
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0839 - val_accuracy: 0.7987 - val_loss: 1.3089
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9528 - loss: 0.1463 - val_accuracy: 0.7987 - val_loss: 1.0086
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9463 - loss: 0.1334 - val_accuracy: 0.8377 - val_loss: 0.8657
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0660 - val_accuracy: 0.8442 - val_loss: 0.8060
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9837 - loss: 0.0558 - val_accuracy: 0.8312 - val_loss: 0.9354
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0402 - val_accuracy: 0.7987 - val_loss: 0.9519
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0283 - val_accuracy: 0.8117 - val_loss: 0.9996
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0145 - val_accuracy: 0.7922 - val_loss: 1.0303
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0111 - val_accuracy: 0.8117 - val_loss: 1.1231
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0099 - val_accuracy: 0.8052 - val_loss: 1.0996
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0149 - val_accuracy: 0.8182 - val_loss: 1.1118
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0221 - val_accuracy: 0.8052 - val_loss: 1.0883
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0098 - val_accuracy: 0.8117 - val_loss: 1.1700
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0165 - val_accuracy: 0.8117 - val_loss: 1.1758
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0081 - val_accuracy: 0.8247 - val_loss: 1.2374
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0150 - val_accuracy: 0.8117 - val_loss: 1.1870
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0173 - val_accuracy: 0.8182 - val_loss: 1.1791
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0268 - val_accuracy: 0.7857 - val_loss: 1.2712
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9935 - loss: 0.0157 - val_accuracy: 0.7987 - val_loss: 1.2683
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9821 - loss: 0.0428 - val_accuracy: 0.8052 - val_loss: 1.1782
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0426 - val_accuracy: 0.7857 - val_loss: 1.4015
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9642 - loss: 0.1170 - val_accuracy: 0.8312 - val_loss: 1.3108
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.2752 - val_accuracy: 0.7532 - val_loss: 1.2049
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2354 - val_accuracy: 0.8117 - val_loss: 1.0434
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9381 - loss: 0.1553 - val_accuracy: 0.7922 - val_loss: 0.7343
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9560 - loss: 0.1068 - val_accuracy: 0.8117 - val_loss: 0.7891
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9658 - loss: 0.1078 - val_accuracy: 0.8312 - val_loss: 0.7272
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9691 - loss: 0.0892 - val_accuracy: 0.8247 - val_loss: 0.8190
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9821 - loss: 0.0532 - val_accuracy: 0.7857 - val_loss: 0.7698
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0403 - val_accuracy: 0.8182 - val_loss: 0.8787
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0195 - val_accuracy: 0.8377 - val_loss: 0.9204
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0152 - val_accuracy: 0.8052 - val_loss: 1.0626
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9967 - loss: 0.0117 - val_accuracy: 0.8052 - val_loss: 1.0818
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0089 - val_accuracy: 0.8052 - val_loss: 1.1277
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0121 - val_accuracy: 0.8052 - val_loss: 1.1518
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0091 - val_accuracy: 0.8182 - val_loss: 1.1661
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0074 - val_accuracy: 0.8052 - val_loss: 1.2159
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0070 - val_accuracy: 0.8052 - val_loss: 1.2318
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0065 - val_accuracy: 0.8052 - val_loss: 1.2560
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0055 - val_accuracy: 0.8052 - val_loss: 1.2771
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0056 - val_accuracy: 0.8052 - val_loss: 1.3432
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0116 - val_accuracy: 0.8182 - val_loss: 1.2838
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0065 - val_accuracy: 0.8117 - val_loss: 1.3417
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0064 - val_accuracy: 0.8117 - val_loss: 1.3535
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0064 - val_accuracy: 0.8052 - val_loss: 1.3421
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.7987 - val_loss: 1.3861
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0052 - val_accuracy: 0.8052 - val_loss: 1.4095
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0050 - val_accuracy: 0.7987 - val_loss: 1.3946
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0052 - val_accuracy: 0.7987 - val_loss: 1.4559
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0083 - val_accuracy: 0.8052 - val_loss: 1.4100
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.2592 - val_accuracy: 0.7338 - val_loss: 2.1943
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.6940 - val_accuracy: 0.7922 - val_loss: 0.6204
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.2965 - val_accuracy: 0.8182 - val_loss: 0.6359
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9251 - loss: 0.1967 - val_accuracy: 0.7987 - val_loss: 0.6771
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9300 - loss: 0.1867 - val_accuracy: 0.8247 - val_loss: 0.7030
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9511 - loss: 0.1183 - val_accuracy: 0.7857 - val_loss: 0.6868